// Code generated by mockery v2.2.1. DO NOT EDIT.

package template

import (
	entities "github.com/maykonlf/scaffold/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigService is an autogenerated mock type for the ConfigService type
type MockConfigService struct {
	mock.Mock
}

// AddTemplate provides a mock function with given fields: template
func (_m *MockConfigService) AddTemplate(template *entities.Template) error {
	ret := _m.Called(template)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Template) error); ok {
		r0 = rf(template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTemplates provides a mock function with given fields:
func (_m *MockConfigService) GetTemplates() ([]*entities.Template, error) {
	ret := _m.Called()

	var r0 []*entities.Template
	if rf, ok := ret.Get(0).(func() []*entities.Template); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Template)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
